# Site settings Copy By Less Or More
name: CharShaw
email: luoyan35714@126.com
author: charshaw

github: https://github.com/charshaw/
baseurl: "/blog"


#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Build settings
markdown: kramdown


